name: Backend (production)

on:
  push:
    branches:
      - main
    paths:
      - apps/backend/**

jobs:
  db-migration:
    name: Database migration
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      - name: Install dependencies
        working-directory: apps/backend
        run: yarn install
      - name: Run migration
        working-directory: apps/backend
        # run: pnpm prisma migrate dev
        run: yarn prisma db push --accept-data-loss
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
  deploy-to-railway:
    needs: db-migration
    uses: ./.github/workflows/railway-deploy.yml
    with:
      environment: production
      working-directory: apps/backend
    secrets: inherit
