name: Frontend (production)

on:
  push:
    branches:
      - main
    paths:
      - apps/frontend/**

jobs:
  deploy-to-vercel:
    uses: ./.github/workflows/vercel-deploy.yml
    with:
      environment: production
      vercel-environment: production
      working-directory: apps/frontend
    secrets: inherit
